### ISSUE TITLE
lodash is >90% of this library size

### ISSUE THREAD

**Issue by Grawl** [pradel/node-instagram#133]
This library is good and easy to use but it put all lodash into my bundle

https://bundlephobia.com/result?p=node-instagram@4.1.0

**Comment by pradel** [comment]
Pull request welcome :)

**Comment by Grawl** [comment]
okay will do it on this week I think

**Comment by Grawl** [comment]
you can use [`size-limit`](https://github.com/ai/size-limit) to avoid of this problem
