### ISSUE TITLE
error TS1192: Module '"events"' has no default export.

### ISSUE THREAD

**Issue by santoshshinde2012** [pradel/node-instagram#148]
When I am trying to build in typescript getting following error,

**node_modules/node-instagram/lib/stream.d.ts:2:8 - error TS1192: Module '"events"' has no default export.**

`2 import EventEmitter from 'events';`

**Comment by pradel** [comment]
This should be fixed in `v4.3.0`.
Feel free to reopen the issue if the problem is still there :)
