### ISSUE TITLE
instagram hashtag search depracted

### ISSUE THREAD

**Issue by hoffmannjan** [pradel/node-instagram#168]
Hi,

after API changes on Instagram side, searching for tags using `/tags/tag/media/recent` stopped working as It is depracated.
Are you planning supporting GraphQL API in your library?

https://developers.facebook.com/blog/post/2018/10/31/instagram-graph-api-hashtag-search-launch/

**Comment by o0alexela0o** [comment]
so is the module dead now?!
without new graphql implementation this pluging is useless.
Please?! any updates?!
thanks

**Comment by pradel** [comment]
Facebook is now unifying all the api under the same graph api see https://developers.facebook.com/docs/instagram-api/hashtag-search, you should consider using a nodejs Facebook client instead of this lib

**Comment by thilinadinith** [comment]
can u please tell me how to do it ?  and tits really sad that your library not supporting this feature :(

**Comment by pradel** [comment]
I am closing the issues in this repo:
The legacy Instagram API is deprecated and will be disabled on June 29, 2020. More information instagram.com/developer.
