### ISSUE TITLE
example express auth throw error: "You must provide a client_id"

### ISSUE THREAD

**Issue by Glowin** [pradel/node-instagram#24]
I run example [express auth](https://github.com/pradel/node-instagram/tree/master/examples/express-auth), but throw error:

```
{"error_type":"OAuthException","code":400,"error_message":"You must provide a client_id"}
```

I think the problem is header, change  content-type to `application/x-www-form-urlencoded` maybe solve this problem.

refer: https://stackoverflow.com/questions/33541677/instagram-api-unable-to-request-access-token

**Comment by pradel** [comment]
Hey can you try the latest version I just pushed? It should be fixed. Thanks for pointing this issue.

**Comment by Glowin** [comment]
Great, it's fix 400 error, Thank you for your contribution.
