### ISSUE TITLE
Type 'typeof internal' is not a constructor function type.

### ISSUE THREAD

**Issue by hlibco** [pradel/node-instagram#248]
Hi @pradel thanks for the great package!

I wanted to report an issue when compiling a project using `"esModuleInterop": true` in the `tsconfig.json`: 

```
node_modules/node-instagram/lib/stream.d.ts:4:30 - error TS2507:
Type 'typeof internal' is not a constructor function type.
declare class Stream extends EventEmitter {
```

**Comment by pradel** [comment]
I am closing the issues in this repo:
The legacy Instagram API is deprecated and will be disabled on June 29, 2020. More information instagram.com/developer.
