### ISSUE TITLE
Cors issue 

### ISSUE THREAD

**Issue by katawura** [pradel/node-instagram#5]
having some weird cors issues with this plugin.

Any way around it guys?

news:1 Fetch API cannot load https://api.instagram.com/v1/users/self/media/recent/?count=2&access_token=TOKEN. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by pradel** [comment]
Hey, are you trying to use this module in a browser directly?
