### ISSUE TITLE
Instagram Data values retrival

### ISSUE THREAD

**Issue by trino2** [pradel/node-instagram#55]
Hello, I am using this library in node.js and running express and when I console log data in js file I get the data but when I pass the data to jade I keep getting [object Object]. I am using a each loop for the values but I cant get certain values like id or likes only.

**Comment by pradel** [comment]
I have never used jade but are you sure you there is no sub objects when you try to access the data?

**Comment by trino2** [comment]
I though it might be that, when I use the console.log to see the data it has {"pagination: {}, data: [{}]}. How do you get the data only or delete the first sub object? Thanks for getting back to me, I appreciate all the help I can get

**Comment by pradel** [comment]
can you provide your jade template and the function you use to inject the data inside the tempate?

**Comment by trino2** [comment]
I figured out what the issue was, When making the API call it would return a array with 3 different arrays in data. I did not see it when all the data was displayed in the console. I just wrote a loop to filter out the first empty array and the meta array and get data only. It works perfectly now, thanks for your help I appreciate your time!
