### ISSUE TITLE
await is a reserved word

### ISSUE THREAD

**Issue by DavidRoca** [pradel/node-instagram#8]
Hi, I am trying to use node-instagram but I am getting the error "await is a reserved word" with this in my code. If I remove "await" I'm getting a 400 code error (myId and myToken are the id and token from my instagram). Am I doing something wrong ? Thanks.

```
import Instagram from 'node-instagram';

// Create a new instance.
const instagram = new Instagram({
  clientId: 'myId',
  accessToken: 'myToken',
});

// You can use callbacks or promises
instagram.get('users/self', (err, data) => {
  console.log(data);
});

// Get information about the owner of the access_token.
const data = await instagram.get('users/self');
console.log(data);
```

**Comment by pradel** [comment]
Can you provide a snippet showing how you try to use this module?

**Comment by penguoir** [comment]
You cannot use `await` outside of a function. It must be in the scope of an `async` function. In this case, your best chance is to replace

```javascript
const data = await instagram.get('users/self');
console.log(data);
```

with

```javascript
instagram.get('users/self').then(data => {
  console.log(data);
}
```
