### ISSUE TITLE
live video streaming?

### ISSUE THREAD

**Issue by 10S10** [pradel/node-instagram#93]
Is this lib able to upload the live video streaming to Instagram from a desktop app like OBS or wireCast?

**Comment by pradel** [comment]
Hey, it looks like live broadcasting is not supported in the API right now.

**Comment by 10S10** [comment]
@pradel It's supporting in the PHP lib, so It would be possible for js lib too I guess

https://github.com/mgp25/Instagram-API/issues/1475

**Comment by pradel** [comment]
`This is Instagram's private API` it's unfortunately unsupported in the public api so the private api may change at any time :(
